version: '3.9'
services:
  atm10-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER_PACK_URL: ${SERVER_PACK_URL-}
    container_name: atm10-server
    environment:
      # URL to download the ATM10 server pack zip (from CurseForge/Modrinth/etc.). Fill it up
      - SERVER_PACK_URL=https://mediafilez.forgecdn.net/files/6921/537/ServerFiles-4.10.zip
      # Java memory
      - JVM_MIN_MEMORY=2G
      - JVM_MAX_MEMORY=6G
      # EULA acceptance
      - EULA=false
      # Comma-separated list of Minecraft usernames or UUIDs to grant OP
      - DEFAULT_OPS=
      # Optional update behavior
      - WIPE_CONFIG=false
      # - WIPE_DIRS="libraries mods packmenu kubejs defaultconfigs"
      - WIPE_DIRS=
        - libraries/
        - mods/
        - packmenu/
        - kubejs/
        - defaultconfigs/
      # RCON and server port
      - ENABLE_RCON=true
      - RCON_PORT=25575
      - RCON_PASSWORD=
      - SERVER_PORT=25565
      - TZ=UTC
    ports:
    # - "public_port(can change):internal_port(fixed)"
      - "25565:25565"
      - "25575:25575"
    volumes:
      - mc_data:/data
    restart: unless-stopped
    stdin_open: true
    tty: true
    stop_grace_period: 2m

volumes:
  mc_data:
    name: mc_data